name = "Statistics_in_Lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["StatisticsInLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "CLT"
git = "https://github.com/Qulinecier/CLT.git"
rev = "master"

[[lean_lib]]
name = "StatisticsInLean"
